version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name CICD --s3-location s3://cicd-t-man/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src